//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cardealership.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Автомобили
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Автомобили()
        {
            this.Продажи_автомобилей = new HashSet<Продажи_автомобилей>();
        }
    
        public int Номер_автомобиля { get; set; }
        public int Марка { get; set; }
        public int Год_производства { get; set; }
        public string Цвет { get; set; }
        public int Категория { get; set; }
        public decimal Цена { get; set; }
        public string Модель { get; set; }
        public string Фото { get; set; }
    
        public virtual Категории_автомобилей Категории_автомобилей { get; set; }
        public virtual Марки_автомобилей Марки_автомобилей { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продажи_автомобилей> Продажи_автомобилей { get; set; }
    }
}
