//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cardealership.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Покупатели
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Покупатели()
        {
            this.Продажи_автомобилей = new HashSet<Продажи_автомобилей>();
        }
    
        public int Номер_покупателя { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Паспортные_данные { get; set; }
        public string Адрес { get; set; }
        public string Город { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public string Пол { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продажи_автомобилей> Продажи_автомобилей { get; set; }
    }
}
