//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cardealership.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продажи_автомобилей
    {
        public int Номер_продажи { get; set; }
        public System.DateTime Дата { get; set; }
        public int Сотрудник { get; set; }
        public int Автомобиль { get; set; }
        public int Покупатель { get; set; }
    
        public virtual Автомобили Автомобили { get; set; }
        public virtual Покупатели Покупатели { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
